Update connect-adfs-wap-report-server.md
MicrosoftDocs/powerbi-docs pull request #2544
Opened 2020-10-09 21:00 UTC by robroyle427

Steps 8 cmdlet isn't the same is the Image above it or below it.  The name could be removed altogether and the cmdlet would return   The picture above has PBIRSWAP.  And the PowerShell command image below has no name specified.  This could be confusing.

2020-10-09 21:01 UTC, PRMerger6 commented
@robroyle427 : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-11 16:20 UTC, JoshGer reviewed
Looked up the Get-WebApplicationProxyApplication cmdlet doc and the requested update is not entirely correct as it needs to include the Name property. So it should be this:

Get-WebApplicationProxyApplication -Name "PBIRSWAP" | FL

I also updated the PowerShell image to reflect the updated command so it matches and sent image to Maggie.

2020-10-13 01:16 UTC, maggiesMSFT requested changes
update

2020-10-13 01:16 UTC, maggiesMSFT commented on powerbi-docs/report-server/connect-adfs-wap-report-server.md
> +    Get-WebApplicationProxyApplication "PBIRSWAP" | FL
```suggestion
    Get-WebApplicationProxyApplication -Name "PBIRSWAP" | FL
```

2020-10-13 01:17 UTC, PRMerger9 commented
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-13 01:17 UTC, PRMerger9 commented
@maggiesMSFT : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-13 01:18 UTC, maggiesMSFT commented
Thanks for bringing this to our attention, @robroyle427 ! After checking with the product team, it needed to be modified a bit. It also needs an updated image, which I'll do separately. Thanks!

2020-10-13 01:19 UTC, merged