Update fetch-more-data.md
MicrosoftDocs/powerbi-docs pull request #2569
Opened 2020-10-21 06:53 UTC by AsafMozes

Added incremental updates mode

2020-10-21 06:53 UTC, PRMerger19 commented
@AsafMozes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-21 12:21 UTC, AviSander commented on powerbi-docs/developer/visuals/fetch-more-data.md
> +Therefore, dataviews sizes are expected to grow on each update.
dataview

2020-10-21 12:21 UTC, AviSander commented on powerbi-docs/developer/visuals/fetch-more-data.md
> +Therefore, dataviews sizes are expected to grow on each update.
grow WITH each update

2020-10-21 12:22 UTC, AviSander commented on powerbi-docs/developer/visuals/fetch-more-data.md
> +Therefore, dataviews sizes are to be limited according to the defined window size.
dataview

2020-10-21 12:24 UTC, AviSander commented on powerbi-docs/developer/visuals/fetch-more-data.md
> +> N can be determined by: (dataView.table['lastMergeIndex'] === undefined) ? 0 : dataView.table['lastMergeIndex'] + 1
i think an example dataview is in place here to demonstrate what should be expected

2020-10-21 12:26 UTC, AviSander commented on powerbi-docs/developer/visuals/fetch-more-data.md
> +
as discussed, let's add API limitations\boundaries: 

- reminder 30K rows is maximum 

- max 1M rows enforced by the server

- max 100MB dataview size enforced by the client

2020-10-21 12:28 UTC, AviSander requested changes
see comments

2020-10-21 16:13 UTC, PRMerger9 commented
@AsafMozes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-21 16:15 UTC, PRMerger9 commented
@AsafMozes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-21 16:19 UTC, PRMerger10 commented
@AsafMozes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-22 15:36 UTC, AviSander commented on powerbi-docs/developer/visuals/fetch-more-data.md
> +> Altough the dataviews data between the different update is mostly exclusive, there will be some overlap between subsequent dataviews.
Although

2020-10-22 15:38 UTC, AviSander approved these changes
one last typo

2020-10-22 15:49 UTC, PRMerger18 commented
@AsafMozes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-23 21:29 UTC, PRMerger13 commented
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-23 21:31 UTC, ktoliver commented
@AviSander Thanks very much for your review of the PR. In the public repo, PRs need to be approved by a member of the content team or the PM for the service.

@KesemSharabi Could you review the PR? Thanks.

2020-10-25 08:01 UTC, KesemSharabi commented
#sign-off

2020-10-26 07:38 UTC, PRMerger15 commented
@AsafMozes : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-26 11:54 UTC, KesemSharabi commented
#hold-off

Please don't publish this article until 10 November.

Thanks,

Kesem

2020-10-26 14:48 UTC, ktoliver commented
> #hold-off
> 
> Please don't publish this article until 10 November.
> 
> Thanks,
> 
> Kesem

Hi @KesemSharabi - We don't have a schedule-based publishing pipeline available, but we will leave this in the queue until you sign off again. Note that this PR is in the public repo and visible to all GitHub users.

-PR review team

2020-10-26 15:03 UTC, PRMerger6 commented
@ktoliver : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2020-10-28 06:40 UTC, KesemSharabi commented
Hi @AsafMozes, @AviSander, @ktoliver and @maggiesMSFT,

I understood from Ranin yesterday that she wants this article published on 10 November, just before her blog post goes live. As this is a public repo and we try to keep PRs on it closed, I opened my own PR on my private repo with the content of this file (fetch-more-data.md). I'll publish my PR on 10 November and we will close this one.

My PR is:

https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/4691

@maggiesMSFT - please go ahead and close this PR.

Thanks,

Kesem

2020-10-28 15:24 UTC, closed without merging

2020-10-28 16:21 UTC, maggiesMSFT commented
Thanks, @KesemSharabi , @AsafMozes , and @AviSander !