Update migrate-azure-analysis-services-to-powerbi-premium.md
MicrosoftDocs/powerbi-docs pull request #3982
Opened 2022-08-02 16:53 UTC by ogetchie

Updated to show Server properties are in PBI in public preview

2022-08-02 16:53 UTC, PRMerger14 commented
@ogetchie : Thanks for your contribution! The author(s) have been notified to review your proposed change.

2022-08-02 20:49 UTC, Jak-MS commented
@peter-myers 

Can you review this PR?

IMPORTANT: When this content is ready to merge, you must add `#sign-off` in a comment or the approval may get overlooked.


#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2022-08-02 22:00 UTC, peter-myers commented on powerbi-docs/guidance/migrate-azure-analysis-services-to-powerbi-premium.md
> +| [Server properties](/analysis-services/server-properties/server-properties-in-analysis-services), which control Analysis Services server instance properties | Yes | Yes <sup>2</sup> |
The footnote "2" needs to be removed also. Remove " <sup>2</sup>".

2022-08-02 22:01 UTC, peter-myers requested changes
See my comment about removing the "2" superscript.

2022-08-04 23:41 UTC, maggiesMSFT commented
Closing. Change is in https://github.com/MicrosoftDocs/powerbi-docs-pr/pull/8296

2022-08-04 23:41 UTC, closed without merging