Update end-user-pdf.md
MicrosoftDocs/powerbi-docs pull request #4151
Opened 2022-10-27 12:36 UTC by Saurabh0507

"Export to PDF for ArcGIS map visuals from Power BI Desktop is currently not supported." point has been added under 'Considerations and limitations'. This was an action item for: https://hybridbi-csi.visualstudio.com/SR%20Actions%20-%20MD/_workitems/edit/227
Reference case: 2109070040006768.

2022-10-27 12:40 UTC, opbld31 commented
Learn Build status updates of commit _[7d128ee](https://github.com/Saurabh0507/powerbi-docs/commits/7d128ee24a3033f4b41280c7ea819943967be58d)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[powerbi-docs/consumer/end-user-pdf.md](https://github.com/Saurabh0507/powerbi-docs/blob/patch-1/powerbi-docs/consumer/end-user-pdf.md) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://buildapi.docs.microsoft.com/Output/PullRequest/7e73b3b4-c8df-fe89-96f8-0be8f719f9ea/202210271236266710-4151/BuildReport?accessString=761119c23e5522c8e8d98249108dd0eeeddcc5a8090af9a5086fef0cb23bfcf6).

**Note:** Broken links written as relative paths are included in the above build report. For broken links written as absolute paths or external URLs, see the [broken link report](https://ops.microsoft.com/#/repos/7e73b3b4-c8df-fe89-96f8-0be8f719f9ea?tabName=brokenlinks).

For any questions, please:<ul><li>Try searching the learn.microsoft.com <a href="https://review.learn.microsoft.com/en-us/help/?branch=main">contributor guides</a></li><li>Post your question in the <a href="https://teams.microsoft.com/l/channel/19%3a7ecffca1166a4a3986fed528cf0870ee%40thread.skype/General?groupId=de9ddba4-2574-4830-87ed-41668c07a1ca&amp;tenantId=72f98bf-86f1-41af-91ab-2d7cd011db47">Learn support channel</a></li></ul>

2022-10-27 15:17 UTC, Court72 commented
@mihart

Can you review the proposed changes? *IMPORTANT*: When the changes are ready for publication, add a `#sign-off` comment to signal that the PR is ready for the review team to merge. 

#label:"aq-pr-triaged"
@MicrosoftDocs/public-repo-pr-review-team

2022-11-01 19:32 UTC, mihart requested changes
Hi Saurabh,
Thank you for creating this.  Please remove the bullet item above yours, the one that reads "The ESRI visual is not supported."  Since the ESRI visual is the same as the ArcGIS visual, we only need to mention it once and your bullet item is more descriptive, so let's keep that one.

2022-11-01 19:58 UTC, mihart commented
Hi @Saurabh0507 ,
I moved your suggestion to the private repo and set it to publish.  No action needed from you :-)  In the future, you can make changes in the private repo powerbi-docs-pr since you are a Microsoft employee.  I've emailed you instructions.  Thanks!

2022-11-01 19:58 UTC, closed without merging